#Dockerfile.exporter
FROM python:3.11-slim
WORKDIR /app
COPY requirements.exporter.txt .
RUN pip install --no-cache-dir -r requirements.exporter.txt
RUN apt-get update && apt-get install -y \
    gcc \
    libpq-dev \
    && rm -rf /var/lib/apt/lists/*
COPY . .
CMD ["python", "export_to_clickhouse.py"]